### ISSUE TITLE
Kustomize fails to install in stdlib load tests

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-performance-cloud#10904]
**Description:**
In the load tests, i have seen recently that the installing kustomize step fails several times. (We are running load tests at different times of the day to avoid workflow queues).

Following is the error log.
```
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
```

https://github.com/ballerina-platform/ballerina-performance-cloud/actions/runs/4050253195/jobs/6967526305#step:10:8
https://github.com/ballerina-platform/ballerina-performance-cloud/actions/runs/4048224591/jobs/6963265690#step:10:9
https://github.com/ballerina-platform/ballerina-performance-cloud/actions/runs/4050019148/jobs/6967067536#step:10:9

**Comment by dilanSachi** [comment]
Looks like this is still failing with rate limit error
https://github.com/ballerina-platform/ballerina-performance-cloud/actions/runs/4249057527/jobs/7388900843

**Comment by anuruddhal** [comment]
Closing as this is no longer valid.
