### ISSUE TITLE
No notification in case of a failure

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-performance-cloud#2687]
As per the current design once triggered from an external repo, the results get committed to a temporary branch in the repo as expected. 

However, in the case of failure, there is no notification of failure returned to the external repo. I think, regardless of the result we should commit those to the temporary branch. For instance, in the case of failure, the committed values could `-1`. Indicating something wrong.

**Comment by shafreenAnfar** [comment]
@niveathika @ThisaruGuruge if you guys can think of a better approach, do comment here.

**Comment by niveathika** [comment]
Cant, we improve this such that for all scenarios the workflow will notify a different workflow in the external directory? This can then do the needful. In case of success commit the results. In case of failure, notify or tag releavant folks.

Please see https://github.com/ballerina-platform/ballerina-standard-library/issues/2371

**Comment by shafreenAnfar** [comment]
@niveathika so the only difference is instead of committing the results, the perf workflow should send a request as below with the results (which could be success or failure).

```
curl -X POST \
    -H "Accept: application/vnd.github.v3+json" \
    -H "Authorization: token <token>" \
    --data '{"event_type": "build", "client_payload": { "status": "success", "result": "1,2,3"}}' \
    https://api.github.com/repos/jannekem/actions-playground/dispatches
```
